### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by JefferiesTube** [CoinK0in/mkdocs-encryptcontent-plugin#15]
I added the plugin to my mkdocs.yml and added a password meta tag to a single page for a test.

```
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tom\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python38\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\serve.py", line 54, in serve
    config = builder()
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\build.py", line 284, in build
    _populate_page(file.page, config, files, dirty)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\commands\build.py", line 177, in _populate_page
    page.content = config['plugins'].run_event(
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\encryptcontent\plugin.py", line 243, in on_page_content
    html = self.__encrypt_content__(html)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\encryptcontent\plugin.py", line 92, in __encrypt_content__
    ciphertext_bundle = self.__encrypt_text_aes__(content, self.password)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\encryptcontent\plugin.py", line 79, in __encrypt_text_aes__
    cipher = AES.new(self.__hash_md5__(password), AES.MODE_CBC, iv)
  File "c:\users\tom\appdata\local\programs\python\python38\lib\site-packages\encryptcontent\plugin.py", line 70, in __hash_md5__
    key.update(text.encode('utf-8'))
AttributeError: 'int' object has no attribute 'encode'
```

However, Mkdocs instantly crashes with the above callstack. (Used OS is Windows, Theme is Material for MkDocs)

**Comment by JefferiesTube** [comment]
Args, after hours of searching it's my own lazyness. I used 123 as a test password but was missing the quotes.
